# Generated by Django 5.1 on 2024-11-06 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campana',
            name='empresa',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
